### ISSUE TITLE
redo motor driver code for esp32 using analogWrite library?

### ISSUE THREAD

**Issue by joshua-8** [joshua-8/JMotor#35]
https://github.com/ERROPiX/ESP32_AnalogWrite

**Comment by Dlloydev** [comment]
...another [analogWrite](https://github.com/Dlloydev/ESP32-ESP32S2-AnalogWrite) library to try that I've just finished testing. Should play nicely with other libraries and code as it will not attach and use a pin and timer that's already been accessed by other code. A unique aspect is that it can shift the PWM with phase control ... can mix RGB colors this way or create a quadrature PWM signal, add deadtime, etc. Note ... LEDC isn't synchronized as with MCPWM but could be useful for lower frequency signals.

Works as basic Arduino style analogWrite, allows other libraries that use analogWrite to compile, works with DAC outputs also.

**Comment by joshua-8** [comment]
Thank you so much for the recommendation! I'll try using your library, and probably add it as a dependency.

**Comment by joshua-8** [comment]
Thanks @Dlloydev for the great library (and for quickly fixing a couple issues with it). My code that was written for standard Arduinos seems to be working on an esp32 now, when I import your library!
